import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/library/theme/theme.tsx";
import { Navbar } from "@/library/nav/nav";
import { Providers } from "./providers";
import { ThemeProvider } from "@/library/theme/theme.tsx";


const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});


const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});


export const metadata: Metadata = {
	title: "MicroMaker",
	description: "Generated by create next app",
};


export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" color-theme="light" className="bg-(--color1) text-(--color2)" >
			<ThemeProvider>
			<Providers>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased bg-(--color1) text-(--color2)`}
				>
					<Navbar />
					{children}
				</body>
			</Providers>
			</ThemeProvider>
		</html>
	);
}

