import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/library/theme/theme";
import { Navbar } from "@/library/nav/nav";
import { Providers, ToastProvider } from "./providers";
import { ThemeProvider } from "@/library/theme/theme";
import { AuthProvider } from "@/library/auth/context";
import { Footer } from "@/library/nav/footer";
import { NavProvider } from "@/library/nav/context";
import { Inter, Berkshire_Swash, Google_Sans_Code, Merienda, Merriweather } from "next/font/google";





const merienda = Merienda({
	variable: "--font-merienda",
	subsets: ["latin"],
	weight: "400",
});

const googleSansCode = Google_Sans_Code({
	variable: "--font-google-sans-code",
	subsets: ["latin"],
	weight: "400",
});

const berkshireSwash = Berkshire_Swash({
	variable: "--font-berkshire-swash",
	weight: "400",
	subsets: ["latin"],
});

const merriweather = Merriweather({
	variable: "--font-merriweather",
	weight: "400",
	subsets: ["latin"],
});


export const metadata: Metadata = {
	title: "MicroMaker",
	description: "Generated by create next app",
};


export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" color-theme="light" className="bg-(--color1) text-(--color2)" >
			<body
				className={`${ merriweather.className } bg-(--color1) text-(--color2)`}
			>
				<ToastProvider />

				<ThemeProvider>
					<Providers>
						<AuthProvider>
							<NavProvider>

							<Navbar />
							{children}
							<Footer />

							</NavProvider>

						</AuthProvider>
					</Providers>
				</ThemeProvider>
			</body>
		</html>
	);
}

